[package]
name = "agpu-pp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agpu = { path = "../" }
bytemuck = "1.7"